name: flutter_pokedex
description: Pokedex using PokeAPI
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: 8.1.2
  deep_pick: 1.0.0
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: 9.1.3
  intl: 0.18.1
  path_provider: 2.1.2
  pokedex_repository:
    path: packages/pokedex_repository

dev_dependencies:
  bloc_test: 9.1.6
  flutter_test:
    sdk: flutter
  lint: 2.3.0
  mocktail: 1.0.3

flutter:
  uses-material-design: true
  generate: true
